[tool]
[tool.git]
source = "~/Documents/config/config/.gitconfig"
target = "~/.gitconfig"

[tool.tmux]
source = "~/Documents/config/config/.tmux.conf"
target = "~/.tmux.conf"

[tool.tmux_tokyonight]
source = "~/Documents/config/config/.tmux-tokyonight"
target = "~/.tmux-tokyonight"

[tool.tmux_cmd]
source = "~/Documents/config/config/.tmux-cht-command"
target = "~/.tmux-cht-command"

[tool.tmux_lang]
source = "~/Documents/config/config/.tmux-cht-languages"
target = "~/.tmux-cht-languages"

[tool.scripts_cht]
source = "~/Documents/config/config/scripts/tmux-cht.sh"
target = "~/.local/bin/tmux-cht.sh"

[tool.scripts_ssh_spawn]
source = "~/Documents/config/config/scripts/ssh_spawn"
target = "~/.local/bin/ssh_spawn"

[tool.scripts_session_switch]
source = "~/Documents/config/config/scripts/dswitch"
target = "~/.local/bin/dswitch"

[tool.scripts_starship_toggle]
source = "~/Documents/config/config/scripts/starship_toggle"
target = "~/.local/bin/starship_toggle"

[tool.starship_toggle_list]
source = "~/Documents/config/config/.starship-modules"
target = "~/.starship-modules"

[tool.neovim]
source = "~/Documents/config/config/nvim"
target = "~/.config/nvim"

[tool.zshenv]
source = "~/Documents/config/config/.zshenv"
target = "~/.zshenv"


[tool.zshrc]
source = "~/Documents/config/config/.zshrc"
target = "~/.zshrc"

[tool.hatch]
source = "~/Documents/config/config/hatch_config.toml"
target = "$XDG_CONFIG_HOME/hatch"

[tool.starship]
source = "~/Documents/config/config/starship.toml"
target = "~/.config/starship.toml"

# TODO: feat: OS specific target
#[target.unix]
#target = "$XDG_CONFIG_HOME/hatch"
#[target.macos]
#target = "~/Library/Application Support/hatch"

[tool.scripts_delete_git_branches]
source = "~/Documents/config/config/scripts/delete_git_branches"
target = "~/.local/bin/delete_git_branches"

[tool.kubeswitch]
source = "~/Documents/config/config/kubeswitch.config.yaml"
target = "~/.kube/switch-config.yaml"

