[tool]
[tool.git]
source = "~/Documents/config/config/.gitconfig"
target = "~/.gitconfig"

[tool.tmux]
source = "~/Documents/config/config/.tmux.conf"
target = "~/.tmux.conf"

[tool.tmux_cmd]
source = "~/Documents/config/config/.tmux-cht-command"
target = "~/.tmux-cht-command"

[tool.tmux_lang]
source = "~/Documents/config/config/.tmux-cht-languages"
target = "~/.tmux-cht-languages"

[tool.scripts_cht]
source = "~/Documents/config/config/scripts/tmux-cht.sh"
target = "~/.local/bin/tmux-cht.sh"

[tool.neovim]
source = "~/Documents/config/config/nvim"
target = "~/.config/nvim"

[tool.zshenv]
source = "~/Documents/config/config/.zshenv"
target = "~/.zshenv"


[tool.zshrc]
source = "~/Documents/config/config/.zshrc"
target = "~/.zshrc"
