#!/usr/bin/env bash
# 
# Fuzzy aws-context switcher.
#
# This script should not be ran directly, but sourced in .zshrc.
function aswitch() {
    # argument provided
    if [ -n "$1" ]; then
        export AWS_PROFILE="$1"
        return 0
    fi
    # no argument provided
    selected=$(aws configure list-profiles | fzf)
    if [[ -z $selected ]]; then
        return 0
    fi
    export AWS_PROFILE=$selected
}
